# Site settings
title: Technological Musings
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A place towrite some ideas about technology which may include scathing rants and objective analysis.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://eric-vargo.github.io" # the base hostname & protocol for your site
github_username:  eric-vargo

# Build settings
markdown: kramdown
